
py = {
    " ": {"typ": "space","end": ""},
    "\n": {"typ": "newline", "end": ""},
    ".": {"typ": "newline", "end": ""},
    ",": {"typ": "newline", "end": ""},
    ":": {"typ": "newline", "end": ""},
    "\'": {"typ": "token", "end": ""},
    "\"": {"typ": "token", "end": ""},
    "+": {"typ": "token", "end": ""},
    "-": {"typ": "token", "end": ""},
    "*": {"typ": "token", "end": ""},
    "/": {"typ": "token", "end": ""},
    "&": {"typ": "token", "end": ""},
    "|": {"typ": "token", "end": ""},
    "=": {"typ": "token", "end": ""},
    "!=": {"typ": "token", "end": ""},
    "<": {"typ": "token", "end": ""},
    ">": {"typ": "token", "end": ""},
    "(": {"typ": "token", "end": ""},
    ")": {"typ": "token", "end": ""},
    "[": {"typ": "token", "end": ""},
    "]": {"typ": "token", "end": ""},
    "{": {"typ": "token", "end": ""},
    "}": {"typ": "token", "end": ""},
    "{": {"typ": "token", "end": ""},
    "def": {"typ": "keyword", "end": " ("},
    "in": {"typ": "keyword", "end": " "},
    "is": {"typ": "keyword", "end": " "},
    "for": {"typ": "keyword", "end": " "},
    "and": {"typ": "keyword", "end": " ("},
    "or": {"typ": "keyword", "end": " ("},
    "if": {"typ": "keyword", "end": " ("},
    "elif": {"typ": "keyword", "end": " ("},
    "else": {"typ": "keyword", "end": " :"},
    "len": {"typ": "keyword", "end": " ("},
    "str": {"typ": "keyword", "end": " ("},
    "pass": {"typ": "keyword", "end": " "},
    "print": {"typ": "keyword", "end": " ("},
    "True": {"typ": "keyword", "end": " "},
    "False": {"typ": "keyword", "end": " "},
}