#!/bin/bash

latex_file="$(realpath "$1")"
latex_filename="${latex_file##*/}"
filename_without_ext="${latex_filename%.*}"

cd tmp
xelatex -shell-escape -interaction=nonstopmode "${latex_file}"
mv -v "${filename_without_ext}.pdf" ../built

